name: deploy-mysql-api

on:
  push:
    branches: ["master"]

jobs:
  deploy-mysql-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: echo 'hello world ...'
      - run: ls -la
      - run: touch .env
      - run: echo 'DATABASE_URL=${{secrets.PG_CONN}}'  >> .env
      - run: echo 'TEST_DATABASE_URL=${{secrets.PG_CONN}}'  >> .env
      - run: echo 'TEST_DATABASE_URL=${{secrets.PG_CONN}}'  >> .env
      - run: cat .env
      
      - run: npm install
      - run: npm install -g sequelize-cli@6.2.0 
      
      - run: sequelize db:migrate

      - run: docker build -t josealan2119/mysql-restapi:${{github.sha}} .
      - run: docker images
   
      - name: docker login
        env:
          DOCKER_USER: ${{secrets.DOCKER_USER}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run:  docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
        
      - name: docker push
        run:  docker push ${{ secrets.DOCKER_USER}}/mysql-restapi:${{github.sha}}
